import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import {
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Download,
  MapPin,
  FileText,
  RefreshCw,
} from "lucide-react";
import HospitalSuggestions from "./HospitalSuggestions";

interface DiagnosisResultsProps {
  diagnosis: any;
  patientInfo: any;
}

const DiagnosisResults = ({ diagnosis, patientInfo }: DiagnosisResultsProps) => {
  const [generating, setGenerating] = useState(false);
  const { toast } = useToast();

  const predictions = diagnosis.predictions || [];
  const hasCancer = diagnosis.has_cancer;
  const confidenceScore = diagnosis.confidence_score;

  const getStatusIcon = () => {
    if (!hasCancer) return <CheckCircle2 className="h-12 w-12 text-success" />;
    if (confidenceScore > 60) return <XCircle className="h-12 w-12 text-destructive" />;
    return <AlertTriangle className="h-12 w-12 text-warning" />;
  };

  const getStatusColor = () => {
    if (!hasCancer) return "success";
    if (confidenceScore > 60) return "destructive";
    return "warning";
  };

  const getStatusText = () => {
    if (!hasCancer) return "No Cancer Detected";
    if (confidenceScore > 60) return "High Risk Detection";
    return "Moderate Risk Detection";
  };

  const generatePDF = async () => {
    setGenerating(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const doc = new jsPDF();
      
      // Add logo/title
      doc.setFontSize(24);
      doc.setTextColor(37, 99, 235);
      doc.text("X-Ray AI Diagnosis System", 105, 20, { align: "center" });
      
      doc.setFontSize(18);
      doc.setTextColor(0, 0, 0);
      doc.text("Diagnosis Report", 105, 35, { align: "center" });
      
      // Add line separator
      doc.setLineWidth(0.5);
      doc.line(20, 40, 190, 40);
      
      // Patient Details
      doc.setFontSize(14);
      doc.setFont(undefined, "bold");
      doc.text("Patient Information", 20, 50);
      
      doc.setFont(undefined, "normal");
      doc.setFontSize(11);
      doc.text(`Name: ${patientInfo.full_name}`, 20, 60);
      doc.text(`Age: ${patientInfo.age} years`, 20, 67);
      doc.text(`Gender: ${patientInfo.sex}`, 20, 74);
      doc.text(`Date & Time: ${new Date().toLocaleString()}`, 20, 81);
      
      // Diagnosis Results
      doc.setFontSize(14);
      doc.setFont(undefined, "bold");
      doc.text("Diagnosis Results", 20, 95);
      
      doc.setFont(undefined, "normal");
      doc.setFontSize(11);
      
      const status = diagnosis.has_cancer ? "Abnormality Detected" : "No Abnormality Detected";
      if (diagnosis.has_cancer) {
        doc.setTextColor(220, 38, 38);
      } else {
        doc.setTextColor(34, 197, 94);
      }
      doc.text(`Status: ${status}`, 20, 105);
      
      doc.setTextColor(0, 0, 0);
      doc.text(`Top Finding: ${diagnosis.top_prediction}`, 20, 115);
      doc.text(`Confidence Score: ${diagnosis.confidence_score}%`, 20, 122);
      
      // Top Predictions
      doc.setFontSize(14);
      doc.setFont(undefined, "bold");
      doc.text("Detailed Predictions", 20, 135);
      
      doc.setFont(undefined, "normal");
      doc.setFontSize(10);
      let yPos = 145;
      predictions.forEach((pred: any, index: number) => {
        doc.text(`${index + 1}. ${pred.name}: ${(pred.probability * 100).toFixed(1)}%`, 25, yPos);
        yPos += 7;
      });
      
      // Footer
      doc.setLineWidth(0.5);
      doc.line(20, 270, 190, 270);
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by X-Ray AI Diagnosis System", 105, 280, { align: "center" });
      doc.text(`Report ID: ${Date.now()}`, 105, 285, { align: "center" });
      
      // Save report to database
      const { error: reportError } = await supabase
        .from("reports")
        .insert({
          user_id: user.id,
          diagnosis_id: diagnosis.id,
          patient_info_id: patientInfo.id,
          report_url: `local_${Date.now()}`,
          report_data: {
            patient: patientInfo,
            diagnosis: diagnosis,
          },
        });

      if (reportError) throw reportError;

      // Download the PDF
      const fileName = `XRay_Diagnosis_${patientInfo.full_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      toast({
        title: "Success",
        description: "Report generated and downloaded successfully",
      });
    } catch (error: any) {
      console.error("Error generating PDF:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to generate report",
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleNewDiagnosis = () => {
    const confirmed = window.confirm(
      "Starting a new diagnosis will clear the current results. Do you want to continue?"
    );
    if (confirmed) {
      window.location.reload();
    }
  };

  return (
    <div className="space-y-6">
      <Card className="shadow-lg border-2" style={{ borderColor: `hsl(var(--${getStatusColor()}))` }}>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              {getStatusIcon()}
              <div>
                <CardTitle className="text-2xl">{getStatusText()}</CardTitle>
                <CardDescription>AI Analysis Complete</CardDescription>
              </div>
            </div>
            <Badge
              variant={hasCancer ? "destructive" : "default"}
              className="text-lg px-4 py-2"
            >
              {confidenceScore}% Confidence
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <img
                src={diagnosis.image_url}
                alt="Chest X-ray"
                className="rounded-lg shadow-md w-full"
              />
            </div>
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold text-lg mb-3">Top Predictions</h3>
                <div className="space-y-3">
                  {predictions.map((pred: any, index: number) => (
                    <div key={index} className="space-y-1">
                      <div className="flex justify-between text-sm">
                        <span className="font-medium">{pred.name}</span>
                        <span className="text-muted-foreground">
                          {(pred.probability * 100).toFixed(1)}%
                        </span>
                      </div>
                      <Progress value={pred.probability * 100} className="h-2" />
                    </div>
                  ))}
                </div>
              </div>

              {!hasCancer && (
                <div className="bg-success-light border border-success rounded-lg p-4">
                  <p className="text-success-foreground font-medium">
                    ✓ All prediction probabilities are below the cancer detection threshold
                  </p>
                </div>
              )}

              {hasCancer && (
                <div className="bg-destructive-light border border-destructive rounded-lg p-4">
                  <p className="text-destructive-foreground font-medium">
                    ⚠ Potential abnormality detected. Please consult a specialist.
                  </p>
                </div>
              )}
            </div>
          </div>

          <div className="flex gap-3">
            <Button onClick={generatePDF} disabled={generating} size="lg" className="flex-1">
              {generating ? (
                <>Generating...</>
              ) : (
                <>
                  <Download className="mr-2 h-4 w-4" />
                  Print & Save Report
                </>
              )}
            </Button>
            <Button onClick={handleNewDiagnosis} variant="outline" size="lg" className="flex-1">
              <RefreshCw className="mr-2 h-4 w-4" />
              New Diagnosis
            </Button>
          </div>
        </CardContent>
      </Card>

      {hasCancer && <HospitalSuggestions />}
    </div>
  );
};

export default DiagnosisResults;